---
# Path sample tsv
samples: "config/samples.tsv"

# Homo sapiens Reference transcriptome and gene annotation
ref:
  assembly: "GRCh38"
  species: "Homo sapiens"
  fasta_url: "https://ftp.ensembl.org/pub/release-112/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz"
  fasta_path: "resources/data/GRCh38/Homo_sapiens.GRCh38.cdna.all.fa.gz"
  gtf_url: "https://ftp.ensembl.org/pub/release-112/gtf/homo_sapiens/Homo_sapiens.GRCh38.112.chr.gtf.gz"
  gtf_path: "resources/data/GRCh38/Homo_sapiens.GRCh38.112.chr.gtf.gz"
